-- Indices recomendados en docs/CHECKLIST_PRODUCCION.md. La base restaurada
-- desde el export no trae ninguno. Idempotente: se puede correr mas de una vez.

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_INGRESO_BONO_SOLICITANTE')
BEGIN
    CREATE INDEX IX_INGRESO_BONO_SOLICITANTE ON INGRESO_BONO (SOLICITANTE);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_INGRESO_BONO_ESTADO')
BEGIN
    CREATE INDEX IX_INGRESO_BONO_ESTADO ON INGRESO_BONO (ESTADO);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_INGRESO_BONO_EMPRESA_ZONA')
BEGIN
    CREATE INDEX IX_INGRESO_BONO_EMPRESA_ZONA ON INGRESO_BONO (ID_EMPRESA, id_zona);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_VALIDACION_BONO_ID_BONO')
BEGIN
    CREATE INDEX IX_VALIDACION_BONO_ID_BONO ON VALIDACION_BONO (ID_BONO);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_VALIDACION_BONO_VALIDADOR1')
BEGIN
    CREATE INDEX IX_VALIDACION_BONO_VALIDADOR1 ON VALIDACION_BONO (USER_VALIDADOR1);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_VALIDACION_BONO_VALIDADOR2')
BEGIN
    CREATE INDEX IX_VALIDACION_BONO_VALIDADOR2 ON VALIDACION_BONO (USER_VALIDADOR2);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_VALIDACION_BONO_ESTADO')
BEGIN
    CREATE INDEX IX_VALIDACION_BONO_ESTADO ON VALIDACION_BONO (ESTADO);
END
GO

-- Clave de login: debe ser unico. Si esto falla, hay usernames duplicados
-- que hay que resolver antes de poder crear el indice.
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_USUARIOS_USERNAME')
BEGIN
    CREATE UNIQUE INDEX UX_USUARIOS_USERNAME ON USUARIOS (username);
END
GO

-- No unico: hay RUTs reales duplicados en USUARIOS (ver CHECKLIST_PRODUCCION.md).
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_USUARIOS_RUT')
BEGIN
    CREATE INDEX IX_USUARIOS_RUT ON USUARIOS (rut);
END
GO
